/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tarea1 */

#ifndef _Included_tarea1
#define _Included_tarea1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tarea1
 * Method:    suma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_tarea1_suma
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tarea1
 * Method:    multiplicacion
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_tarea1_multiplicacion
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tarea1
 * Method:    resta
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_tarea1_resta
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tarea1
 * Method:    division
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_tarea1_division
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
